
GET http://localhost:8000/ok
###
GET http://localhost:8000/timeout
###
GET http://localhost:8000/houseData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzI1NDIwNzR9.npBJ9uO_lMFChDXbzSZIFeDsv3BNdGWht1SsViehObY
###
GET http://localhost:8000/houseSpecificationsData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzIxOTQ2OTB9.3iMuNSLNhCw7e0DOFBgAyu5eQCIXHCswmbj5Yp-tcWA
###
GET http://localhost:8000/customerSupportTicketsData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzIxOTQ2OTB9.3iMuNSLNhCw7e0DOFBgAyu5eQCIXHCswmbj5Yp-tcWA
###
GET http://localhost:8000/bookings/13
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2JAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjExMzM2NjB9.32FclpnChnwNnnMRZr3waAAOSmMe7j4jnKnlU5xwp1U
######
GET http://localhost:8000/paymentsData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMTU1OTA5NX0.qsPwwz_l1FQWtGpJmflD-WwIWZDIQroxlYuwaTwfqSI

######
GET http://localhost:8000/bookingsData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDg5NTg3MX0.NMlaE09tTkEffoqZKUUZ6c7jU8jPsouLWDYy5MIOZOM
###
GET http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzI1NDIwNzR9.npBJ9uO_lMFChDXbzSZIFeDsv3BNdGWht1SsViehObY
###
GET http://localhost:8000/locationBranches
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDg5NTg3MX0.NMlaE09tTkEffoqZKUUZ6c7jU8jPsouLWDYy5MIOZOM
###
GET http://localhost:8000/locationBranches/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDg5NTg3MX0.NMlaE09tTkEffoqZKUUZ6c7jU8jPsouLWDYy5MIOZOM
###
GET http://localhost:8000/payments
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDg5NTg3MX0.NMlaE09tTkEffoqZKUUZ6c7jU8jPsouLWDYy5MIOZOM
###
GET http://localhost:8000/paymentsData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDg5NTg3MX0.NMlaE09tTkEffoqZKUUZ6c7jU8jPsouLWDYy5MIOZOM
###
GET http://localhost:8000/house/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzI1NDIwNzR9.npBJ9uO_lMFChDXbzSZIFeDsv3BNdGWht1SsViehObY
###
PUT http://localhost:8000/payments/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDg5NTg3MX0.NMlaE09tTkEffoqZKUUZ6c7jU8jPsouLWDYy5MIOZOM

{
  "amount":40000
}
###
DELETE http://localhost:8000/users/10
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDg5NTg3MX0.NMlaE09tTkEffoqZKUUZ6c7jU8jPsouLWDYy5MIOZOM
###
POST http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzIxOTQ2OTB9.3iMuNSLNhCw7e0DOFBgAyu5eQCIXHCswmbj5Yp-tcWA
Content-Type: application/json

{
   
    "full_name": "Abel Kibira",
    "email":"Abil@gmail.com",
    "contact_phone": "+254187324234",
    "address": "marwa, Kenya",
    "password":"password",
    "role":"user"
}
###

POST http://localhost:8000/house
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzI1NDIwNzR9.npBJ9uO_lMFChDXbzSZIFeDsv3BNdGWht1SsViehObY
Content-Type: application/json

{
   
    "houseSpec_id":3,
    "rooms":4,
    "year_built":2023,
    "color":"black",
    "features":"well furnished",
    "bedrooms":2,
    "rental_rate":150000,
    "availability":"available",
    "images":""
}
###
POST http://localhost:8000/create-checkout-session
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJldmFoQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyQWRtaW5Sb2xlQXV0aCIsImV4cCI6MTczMjE5NDQ0M30.FhsuSHIW-m3vRJx57X6mY2hUONIUEThkuQHLrQFmHSE
Content-Type: application/json

{
   
    "booking_id":1,
    "amount": 15000,
    "payment_status": "Pending",
    "payment_method": "Card"
}
###
POST http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJldmFoQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyQWRtaW5Sb2xlQXV0aCIsImV4cCI6MTczMjE5NDQ0M30.FhsuSHIW-m3vRJx57X6mY2hUONIUEThkuQHLrQFmHSE
Content-Type: application/json

{
   
    "full_name": "Abel Kibira",
    "email":"Abel@gmail.com",
    "contact_phone": "+254187324234",
     "address": "marwa, Kenya",
     "password":"password",
     "role":"user"
}
###
PUT http://localhost:8000/houseSpecifications/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzIxOTQ2OTB9.3iMuNSLNhCw7e0DOFBgAyu5eQCIXHCswmbj5Yp-tcWA

{

    "features":"Four bedrooms"
}

###
PUT http://localhost:8000/house/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzIxOTQ2OTB9.3iMuNSLNhCw7e0DOFBgAyu5eQCIXHCswmbj5Yp-tcWA

{
  "images":"https://i.pinimg.com/236x/99/ac/72/99ac72fbd8cf2bf25da13c6b9a45bd85.jpg" 
  
}
###
POST http://localhost:8000/bookings
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzMyNTQyMjM3fQ.ZJBZYCF4Lhpr0VqmpCyORcvhv26l2x3DfusLkdMYxBg
Content-Type: application/json

{
   "user_id": 3,
   "house_id": 2,
   "location_id": 2,
   "booking_date": "2021-2-3",
   "return_date": "2021-2-5",
   "total_amount": 250000
   
}
###
POST http://localhost:8000/customerSupportTickets
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXVsQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzMyNTQzNDgwfQ.Xk4EaDjrz8av8OsdUhb2Hw6cCtoH4r4B6F0glHq0120
Content-Type: application/json

{
   "user_id": 5,
   "subject": "The colour is too dull",
   "description": "sdfghjk",
   "status": "complain"
}
###
POST http://localhost:8000/locationBranches
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYW1hYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzI1NDIwNzR9.npBJ9uO_lMFChDXbzSZIFeDsv3BNdGWht1SsViehObY
Content-Type: application/json

{
   
   "name": "meru",
   "address": "chuka",
   "contact_phone": "765"
   
}

###
POST http://localhost:8000/register
Content-Type: application/json

{
    
   "full_name":"Kamaa",
   "email":"kamaa@gmail.com",
   "password":"password",
   "contact_phone":"09876540987",
   "address":"Nyeri",
   "role":"admin"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"everlyn@gmail.com",
    "password":"password"
}